### ISSUE TITLE
4.0.0 build fails on ios

### ISSUE THREAD

**Issue by deliverymanager** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#601]
Did you test on ios@5.0.1?
The build fails.

```
The following build commands failed:
	CompileC /Users/adomvris/Library/Developer/Xcode/DerivedData/axnikanela-aecsgtpgwdmanqhalsfovkloyltn/Build/Intermediates.noindex/axnikanela.build/Release-iphonesimulator/axnikanela.build/Objects-normal/x86_64/BranchSDK.o /Users/adomvris/projects/buildmobileorderonmac/mobileorder2/axnikanela/mobileorder2/platforms/ios/axnikanela/Plugins/branch-cordova-sdk/BranchSDK.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
```

**Comment by keapick** [comment]
It's in the release notes.  Known issue with cordova and cocoapods.  Workaround is to build from xcode.

https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/releases/tag/v4.0.0

**Comment by Juanperezc** [comment]
Same issue

**Comment by echo-branch** [comment]
Workaround is to build from Xcode.

**Comment by Mapiac** [comment]
@echo-branch can you tell us more about what you know and maybe someone can take it on?

**Comment by echo-branch** [comment]
@Mapiac 
Of course, the root problem is Cordova not work with an XCode build option.  The fix for this is for the Branch iOS SDK to be rearranged, but this has implications in other areas which will take some time to resolve.

A possible workaround is to modify your Cordova iOS to respect this option.  One user reports this worked for them.  https://github.com/apache/cordova-ios/issues/659

Also we finally have new maintainers for Cordova, so we should have an update soonish.

**Comment by Mapiac** [comment]
Thank you @echo-branch Btw is there a place the new maintainers are introduced? Or a blog post I missed?

**Comment by echo-branch** [comment]
This should be resolved in the latest release.

**Comment by AleCat83** [comment]
This is still happening to me in version 4.2.1. I m able to go around this building with Xcode but this force me to remove the plugin when testing with ionic live reload,

**Comment by tamsel12** [comment]
Yes, The Build is failed if i have updated the 4.2.1 version. So i am building with only xcode.
