### ISSUE TITLE
Deeplink in resume doesn't pass data (android resume state)

### ISSUE THREAD

**Issue by mvaullerin** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#622]
Hello,

On Android, when clicking on a deeplink when the app is in resume state, I don't get the deeplink data when calling Branch.initSession(). 

I got this :
```
{
+clicked_branch_link: false,
+is_first_session: false
}
```

Ionic:

   Ionic CLI                     : 5.4.5 (/Users/maxime/.nvm/versions/node/v10.12.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 20 other plugins)

branch-cordova-sdk 4.1.1
cordova-android 8.0.0

Any idea ?

**Comment by FahmiChaar** [comment]
Same issue with
branch-cordova-sdk 4.1.1
cordova-android 8.0.1

**Comment by stefdelec** [comment]
Same problem here

**Comment by FahmiChaar** [comment]
Workaround
For now i just downgrade to 3.2.1 version

**Comment by ArnaudPrigent** [comment]
Same problem

**Comment by mvaullerin** [comment]
> Workaround
> For now i just downgrade to 3.2.1 version

Downgrade to 3.2.1 doesn't change anything for me...
The deeplink works only if the app is closed, not in resume mode.

**Comment by tommymetz** [comment]
Same

**Comment by echo-branch** [comment]
Logged a ticket for this one.  Will try to get eyes on it next sprint.

**Comment by tommymetz** [comment]
BTW I figured out a hack by delaying Branch.initSession() by 1 second. Not ideal but fixed the issue for now.

**Comment by bklastaitis-branch** [comment]
v4.1.3 should fix this

**Comment by tommymetz** [comment]
@bklastaitis-branch great thank you! We'll test it out.

**Comment by mvaullerin** [comment]
> v4.1.3 should fix this

I don't get any change...
Still don't get data in resume state (but working when app is closed).

@bklastaitis-branch, can we help you about this ?

**Comment by tommymetz** [comment]
v4.1.3 fixed it for me.

**Comment by bklastaitis-branch** [comment]
@mvaullerin Would you confirm what what data you do get (in resume state)? Error, callback not invoked, empty referring parameters?

**Comment by mvaullerin** [comment]
I have exactly the same behaviour than previously.
When I console.log Branch.initSession() i got this:
``
{
+clicked_branch_link: false,
+is_first_session: false
}
``

And there is no error. The app run like if it was not triggered by deeplink.
And if I try the deeplink with the app close, I got this :
``
{
+non_branch_link: *the informations I need*,
+clicked_branch_link: false,
+is_first_session: false
}
``

Using : 
"branch-cordova-sdk": "4.1.3"
"@ionic-native/branch-io": "5.21.6"

**Comment by bklastaitis-branch** [comment]
@mvaullerin we cannot reproduce your scenario. Would you reach out to support@branch.io with details such as the link you are using and your BranchKey? Most of the time this is a configuration issue. If support confirms it's not, we will surely get a ticket filed and looked at!

**Comment by mvaullerin** [comment]
@bklastaitis-branch I will contact the support with my issue.

Thanks for your help !

**Comment by razam217** [comment]
Did you guys find any solution to this issue?

**Comment by iamqinglong** [comment]
Hello guys, still experiencing this in version 4.1.3 but in iOS

ENV: 
ionic 4
branch-cordova-sdk 4.1.3
